# Generated by Django 3.1.7 on 2021-03-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210325_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attentionfield',
            options={'ordering': ['name'], 'verbose_name': 'Attention Field'},
        ),
        migrations.AlterModelOptions(
            name='attentionlanguage',
            options={'verbose_name': 'Attention Language'},
        ),
    ]
