# Generated by Django 3.1.7 on 2021-04-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210412_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Follows'},
        ),
    ]
