# Generated by Django 3.1.7 on 2021-04-12 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210412_1916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='FollowRelation',
        ),
        migrations.AlterModelTable(
            name='followrelation',
            table=None,
        ),
    ]
