# Generated by Django 3.1.7 on 2021-04-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210413_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers',
            new_name='followings',
        ),
    ]
