from django.core.management.base import BaseCommand
from users.models import AttentionLanguage


class Command(BaseCommand):

    help = "This command create languages"

    # def add_arguments(self, parser):
    #     parser.add_argument("--times", help="How many times do you want to tell you")

    def handle(self, *args, **options):
        languages = [
            "            ABAP",
            "ActionScript",
            "Ada",
            "ALGOL",
            "Alice",
            "APL",
            "ASP / ASP.NET",
            "Assembly Language",
            "Awk",
            "BBC Basic",
            "C",
            "C++",
            "C#",
            "COBOL",
            "Cascading Style Sheets",
            "D",
            "Delphi",
            "Dreamweaver",
            "Erlang and Elixir",
            "F#",
            "FORTH",
            "FORTRAN",
            "Functional Programming",
            "Go",
            "Haskell",
            "HTML",
            "IDL",
            "INTERCAL",
            "Java",
            "Javascript",
            "jQuery",
            "LabVIEW",
            "Lisp",
            "Logo",
            "MetaQuotes Language",
            "ML",
            "Modula-3",
            "MS Access",
            "MySQL",
            "NXT-G",
            "Object-Oriented Programming",
            "Objective-C",
            "OCaml",
            "Pascal",
            "Perl",
            "PHP",
            "PL/I",
            "PL/SQL",
            "PostgreSQL",
            "PostScript",
            "PROLOG",
            "Pure Data",
            "Python",
            "R",
            "RapidWeaver",
            "RavenDB",
            "Rexx",
            "Ruby on Rails",
            "S-PLUS",
            "SAS",
            "Scala",
            "Sed",
            "SGML",
            "Simula",
            "Smalltalk",
            "SMIL",
            "SNOBOL",
            "SQL",
            "SQLite",
            "SSI",
            "Stata",
            "Swift",
            "Tcl/Tk",
            "TeX and LaTeX",
            "Unified Modeling Language",
            "Unix Shells",
            "Verilog",
            "VHDL",
            "Visual Basic",
            "Visual FoxPro",
            "VRML",
            "WAP/WML",
            "XML",
            "XSL",
        ]
        for l in languages:
            AttentionLanguage.objects.create(name=l)
        self.stdout.write(self.style.SUCCESS("Languages Created"))
