# Generated by Django 3.1.7 on 2021-04-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruit',
            old_name='name',
            new_name='title',
        ),
    ]
