# Generated by Django 3.1.7 on 2021-04-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0002_auto_20210404_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruit',
            old_name='enterprise',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='description',
        ),
        migrations.AddField(
            model_name='recruit',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recruit',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
