# Generated by Django 3.1.7 on 2021-04-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0003_auto_20210410_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
