# Generated by Django 3.1.7 on 2021-04-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20210330_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='recommended',
        ),
        migrations.AddField(
            model_name='board',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
