# Generated by Django 3.1.7 on 2021-04-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20210412_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='name',
        ),
    ]
